# Generated by Django 5.1.2 on 2024-10-21 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_alter_useraccount_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='birthdate',
            new_name='date_of_birth',
        ),
    ]
