# Generated by Django 5.1.2 on 2024-10-24 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_rename_birthdate_useraccount_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
    ]
