# Generated by Django 5.1.2 on 2024-10-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0006_useraccount_is_active_useraccount_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='birthdate'),
        ),
    ]
