# Generated by Django 5.1.2 on 2024-10-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0008_alter_useraccount_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='total_followers',
            field=models.IntegerField(default=0),
        ),
    ]
